### ISSUE TITLE
SerializationError for datetime.time object

### ISSUE THREAD

**Issue by marekmalek** [elasticsearch/elasticsearch-py#185]
JSONSerializer does not support time type.
```
elasticsearch/serializer.py

class JSONSerializer(object):
    mimetype = 'application/json'

    def default(self, data):
        if isinstance(data, (date, datetime)):
            return data.isoformat()
        elif isinstance(data, Decimal):
            return float(data)
        raise TypeError("Unable to serialize %r (type: %s)" % (data, type(data)))
```
 so I get a following error:

```
TypeError("Unable to serialize datetime.time
(10, 34) (type: <type 'datetime.time'>)"
```

A fix is quick and easy. Return time in isoformat like for date and datetime types:
```
class JSONSerializer(object):
    mimetype = 'application/json'

    def default(self, data):
        if isinstance(data, (date, time, datetime)):
            return data.isoformat()
        elif isinstance(data, Decimal):
            return float(data)
        raise TypeError("Unable to serialize %r (type: %s)" % (data, type(data)))
```

**Comment by HonzaKral** [comment]
Hm, I originally didn't include time in the serialization because it may be misleading - we could serialize it automatically exactly as you describe but then elasticsearch won't recognize it and store it as string. To me that's slightly weird and that's why I avoided it, forcing people to deal with it manually.

What do you think, is it ok to just serialize it even when elasticsearch won't recognize it?

**Comment by marekmalek** [comment]
I think if time doesn't have it's on core type in elasticsearch it should be indexed as string. If someone's implementation need different approach then they will take care of it.

**Comment by HonzaKral** [comment]
I understand, I am just worried about the gap - with `datetime` we serialize it from python into string because we know elasticsearch will deserialize it correctly so it's transparent for the user. With `time` it wouldn't be transparent and imho could be very frustrating for the users. This way it fails and forces the user to deal with the situation. In the spirit of "no opinions in the client" I have to close this issue.

If you really want this behavior, it's very easy to subclass `JSONSerializer` and add the `time` handling into its `default` method yourself. You then just pass in a serializer instance into `Elasticsearch` when creating the client instance.

**Comment by zeinababbasi** [comment]
@HonzaKral, would you please explain how to serialize a `datetime` object? Is there any known format like ISO or something else which I can use to provide a datetime object to elasticsearch?

**Comment by HonzaKral** [comment]
@zeinababbasi there is no need to serialize a `datetime` object, `elasticsearch-py` will do it for you automatically (by using `isoformat()`) - see https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/serializer.py#L29 for details

**Comment by zeinababbasi** [comment]
@HonzaKral, thank you. I've tried it yesterday with `isoformat()`. 
BTW, I appreciate your response in a thread which is closed for 2 and a half years.
