### ISSUE TITLE
Spec file for RPM packages

### ISSUE THREAD

**Issue by AndreaGiardini** [elasticsearch/elasticsearch-py#203]
Hi

I'm trying to build an rpm packages for this python module. Would you be interested in a PR with the specfile?

**Comment by HonzaKral** [comment]
Hi, thanks for the offer, it is appreciated, but I don't think a specfile belongs into a python repo. Especially since it only has pure python dependencies so it doesn't need to be installed by the OS.

If you create it as a gist, I will be happy to link to it from the readme or docs of course (and would be very happy for such PR). Makes sense?

**Comment by AndreaGiardini** [comment]
Makes sense, i will open a PR to add a link to README then
